### PR TITLE
Less Racy Bad Token Detection

### PR DESCRIPTION
**Pull request by nlordell**
We observed another case of a token being incorrectly flagged as "bad" because we:
- Read the balance on block `N`
- Executed a trace call with the full balance on block `N - 1`, where the balance increased from block `N - 1` to `N`.

This 🤡-patch just makes this less likely to happen by not using the full token balance in the transfer into the settlement contract.

This also would protect against cases where the balance is read on block `N`, and then a new block `N + 1` is observed where the token owner's balance decreases, in between reading the balance and sending the `trace_callMany` call.

### Test Plan

CI. Manual test:
```
% cargo test -p shared -- --ignored trace_call
    Finished test [unoptimized + debuginfo] target(s) in 0.31s
     Running unittests src/lib.rs (target/debug/deps/shared-04565d164529f1fa)

running 2 tests
test bad_token::trace_call::tests::mainnet_univ3 ... ok
test bad_token::trace_call::tests::mainnet_tokens ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 381 filtered out; finished in 41.10s
```

### CODE REVIEW

**Comment by fleupold** [comment]
We do fetch `balance_before_in` as part of our trace call. We could also add a sanity check in the assertions that `balance_before_in` was >= `amount` and in case it's not retry (either with the same or some other solution candidate).

**Review by vkgnosis — APPROVED** [review]
Am fine with this change but also like Felix' suggestion.

**Comment by nlordell** [comment]
> We do fetch balance_before_in as part of our trace call. We could also add a sanity check in the assertions that balance_before_in was >= amount and in case it's not retry (either with the same or some other token owner candidate).

Retry logic 😞... I guess that is a more bullet proof solution, but personally I find this one just "easier" (albeit 🤡-ier).

I think the longer-term solution is to use ["roundtrip" simulation](https://github.com/nlordell/cow-trade-simulation/blob/42222a7b422f5f49b7f8b16c0c2df744bb38603d/contracts/Trader.sol#L87-L160) - which I would prefer implementing over retying with trace-calls. Also, since most of the simulation + override pieces are in place, I do think it is something that could be done next week.

**Comment by sunce86** [comment]
Why not trying with two (or even three) different token owners in parallel?

**Comment by vkgnosis** [comment]
On the other hand it could genuinely be a bad token that is only bad for some addresses. So we shouldn't simulate three times and say the token is good if 1 succeeds and 2 fail. But if we inspect the traced balance and discard those where the balance has changed then it would be ok.

Anyway, Nick's approach is simple and an improvement. We should merge it. Can still do a more sophisticated approach later.

**Comment by nlordell** [comment]
> We do fetch `balance_before_in` as part of our trace call.

It turns out we only fetch this for the settlement contract and not the token owner, so it will be a more involved change.

**Review by MartinquaXD — APPROVED** [review]

**Review by sunce86 — APPROVED** [review]

**Comment by nlordell** [comment]
I implemented @fleupold's suggestions https://github.com/cowprotocol/services/pull/719.

Personally, I'm not a huge fan of retry logic and prefer this simpler solution (because of the additional complexity of the retry version), but it is a little more robust than the current solution.

**Pull request merged**
