### PR TITLE
No liquidity or filtering of non-fee-connected-tokens for external solvers

### PR DESCRIPTION
**Pull request by nlordell**
Patches #454.

One of the external solvers integrating with our protocol noticed that orders that they were explicitly trying to solve for were being filtered out and not sent as part of the instance they were solving for.

Specifically, the external solver integration aimed at handling orders trading specific tokens by entering and exiting on-chain positions instead of the standard swapping with on-chain liquidity. This meant that orders for these tokens were not being passed to the solvers and were being filtered out (since there was no baseline liquidity between those tokens and the fee token) despite the order being allowed (because of existing price estimate). This meant that these orders could never be solved! They can't be handled by our single order solvers and were getting filtered out in the instance that is sent to all external HTTP solvers. This also implies that for orders without Baseline/Quasimodo price estimates that they were never going to external solvers and were only being handled by our single order solvers.

This PR adds a flat that controls whether or not to filter orders with non-fee-connected-tokens for solvers based on baseline liquidity. This allows our optimization solvers (MIP and Quasimodo) to continue to function, as they rely on the fact that no orders on "islands" not connected to the fee token exist, while passing all orders to external solvers (as they should be).

Ideally, we should **stop** filtering out orders in the instance file. Since this requirement is specific to our optimization solvers (MIP and Quasimodo), they should do the filtering themselves internally. However, since this fix is important we shouldn't wait for the required changes to MIP and Quasimodo to just disable the non-fee-connected-tokens order filtering altogether.

### Test Plan

Some manual testing. Start the `orderbook` and `autopilot` and create an order trading a token **without UniswapV2 liquidity**. I just found a random pair and used `0x33d63ba1e57e54779f7ddaeaa7109349344cf5f1` to `0x89d71dfbdd6ebecd0dfe27d55189f903169d2991` (found them by looking through newly deployed UniV3 pairs and checking `getPair` on the UniV2 factory contract).

Start the `solver` with **only UniswapV2** baseline liquidity with an optimization solver and an external HTTP solver, and see that it sends an instance including the order created ☝️ but without any AMMs (this used to be filtered out because it was "not connected to fee token"):
```
cargo run -p solver -- \
  --baseline-sources UniswapV2 \
  --solvers Quasimodo \
  --external-solvers 'Test|http://localhost:9999|0x4242424242424242424242424242424242424242' \
  --solver-account 0x4242424242424242424242424242424242424242 \
  --transaction-strategy DryRun
```

<details><summary>Notice that we send an empty instance to Quasimodo:</summary>

```
{
  "tokens": {
    "0x33d63ba1e57e54779f7ddaeaa7109349344cf5f1": {
      "decimals": 18,
      "alias": "DATA",
      "external_price": 0.012628828654630182,
      "normalize_priority": 0,
      "internal_buffer": "240849371584716781"
    },
    "0x89d71dfbdd6ebecd0dfe27d55189f903169d2991": {
      "decimals": 0,
      "alias": "THDX",
      "external_price": 1785714285714285.8,
      "normalize_priority": 0,
      "internal_buffer": "0"
    }
  },
  "orders": {},
  "amms": {},
  "metadata": {
    "environment": "Ethereum / Mainnet",
    "auction_id": 1,
    "run_id": 1,
    "gas_price": 15268515361.0,
    "native_token": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
  }
}
```

</details>

<details><summary>But that we include the order for the external HTTP solver:</summary>

```
{
  "tokens": {
    "0x33d63ba1e57e54779f7ddaeaa7109349344cf5f1": {
      "decimals": 18,
      "alias": "DATA",
      "external_price": 0.012628828654630182,
      "normalize_priority": 0,
      "internal_buffer": "240849371584716781"
    },
    "0x89d71dfbdd6ebecd0dfe27d55189f903169d2991": {
      "decimals": 0,
      "alias": "THDX",
      "external_price": 1785714285714285.8,
      "normalize_priority": 0,
      "internal_buffer": "0"
    }
  },
  "orders": {
    "0": {
      "sell_token": "0x33d63ba1e57e54779f7ddaeaa7109349344cf5f1",
      "buy_token": "0x89d71dfbdd6ebecd0dfe27d55189f903169d2991",
      "sell_amount": "999351486382391283712",
      "buy_amount": "5238",
      "allow_partial_fill": false,
      "is_sell_order": true,
      "fee": {
        "amount": "648513617608716288",
        "token": "0x33d63ba1e57e54779f7ddaeaa7109349344cf5f1"
      },
      "cost": {
        "amount": "1012531596164715",
        "token": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
      },
      "is_liquidity_order": false,
      "mandatory": false,
      "has_atomic_execution": false
    }
  },
  "amms": {},
  "metadata": {
    "environment": "Ethereum / Mainnet",
    "auction_id": 1,
    "run_id": 1,
    "gas_price": 15268515361.0,
    "native_token": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
  }
}
```

</details>

### CODE REVIEW

**Comment by fleupold** [comment]
> 1. Stops sending AMM liquidity to the external solvers. I verified that none of them were using it (so it just saves bandwidth and makes uploading instances to them faster).

I'm not sure I understand why this is necessary to fix the issue at hand. We have some solvers currently in shadow mode (Stake Capital, RE7, etc) that are definitely working with the baseline liquidity. Moreover, we passed a DAO proposal that requires solvers to at least match users at prices that can be fulfilled using baseline liquidity. This requires - at least in theory - some indication of what that baseline liqiuidity is.

Making a breaking change like this to the instance file needs more careful preparation @harisang (communicating to solvers and giving them time to react).

I hope it is not required to fix the issue at hand.

**Comment by harisang** [comment]
As a clarification, connection to the fee token means connection to WETH (e.g., for mainnet)? I got confused by the "fee" usage here.

Also, I agree with Felix. Why remove baseline liquidity? Do we really save that much on bandwith/speed? I think it's very good to keep it there, as it makes it a good starting point for solvers under development, and also makes it easier to do sanity checks regarding prices a solver computes.

I can let everyone know, but again, I would say that unless we really believe it will have some impact, I would keep baseline liquidity for all solvers.

Regarding the filtering out of orders, I agree with you Nick that we should not filter out anything! This is the job of solvers to decide what to ignore, and we can make sure that MIP/Quasimodo also adapt very quickly to this change.

**Comment by nlordell** [comment]
> I hope it is not required to fix the issue at hand.

Not at all required.

> Moreover, we passed a DAO proposal that requires solvers to at least match users at prices that can be fulfilled using baseline liquidity. This requires - at least in theory - some indication of what that baseline liqiuidity is.

OK. I wasn't aware it was an integral part of the protocol yet.

**Comment by harisang** [comment]
> were being filtered out (since there was no liquidity between those tokens and the fee token) despite the order being allowed (because of existing price estimate).

Does this mean that we somehow have so-called external prices for some of the tokens for which there is no connection to WETH? How can this happen?

**Comment by nlordell** [comment]
> Does this mean that we somehow have so-called external prices for some of the tokens for which there is no connection to WETH? How can this happen?

We have tokens that have no connection to WETH **using baseline liquidity**. If, for example, a token's only connection to WETH is over a UniV3 pool, then it would get filtered out.

**Comment by nlordell** [comment]
@fleupold - I changed this PR to have the flag only affect the filtering of orders without fee token connections.

**Review by vkgnosis — APPROVED** [review]

**Review by MartinquaXD — APPROVED** [review]

**Pull request merged**
