### PR TITLE
Fix whitespace mistakes in database readme

### PR DESCRIPTION
**Pull request by vkgnosis**
Was editing the file for a different reason and wanted to do this in separate PR.

### Test Plan

n/a

### CODE REVIEW

**Comment by vkgnosis** [comment]
I see. Didn't know that trailing space has semantic meaning in markdown. The way I'm used to making a new line in markdown is to have a full empty line. Are you ok with changing the trailing spaces to empty lines? It's a small preference for me.

**Comment by MartinquaXD** [comment]
Those options are not equivalent for the 2 markdown flavors, though. A full empty line will produce a new paragraph whereas 2 spaces will only produce a line break.
I was not able to produce identical layout in github markdown and "regular" markdown without those 2 spaces. But I don't care too much and most people will probably only look at the markdown rendered on github anyway so there is probably no need for the greater compatibility.
Will try to find a markdown viewer that supports the github markdown flavor to use in the future.

**Review by MartinquaXD — APPROVED** [review]

**Comment by vkgnosis** [comment]
Didn't mean to merge without finishing discussion but auto merge was on. I was under the impression that usually a normal line ending is *not* a new line in the rendered view. You *need* to indicate that you want a real new line with a full empty line.

**Comment by MartinquaXD** [comment]
AFAICT only the github markdown renderer behaves like you described for line breaks.
Another thing that is compatible across github markdown and regular markdown is to use a backslash for line breaks.
But if the `\` is followed by an empty line the `\` will actually be rendered so it's easier to make mistakes with that.

**Comment by vkgnosis** [comment]
Markdown doesn't have one specification that is accepted everywhere. The main spec I know is [CommonMark](https://commonmark.org/) . The relevant links there are:

- https://spec.commonmark.org/0.30/#paragraphs
- https://spec.commonmark.org/0.30/#hard-line-break
- https://spec.commonmark.org/0.30/#soft-line-breaks

An empty line separates paragraphs. Two spaces at the end of a line are a hard line break. A normal end of line is a soft line break. How paragraph is visualized is up to the tool but a paragraph almost always ends is at least a line break. Semantically my intention is usually to write paragraphs. I don't want to manually place line breaks. According to this spec then I should write a full paragraph in one line (to not induce soft line breaks) and end it with an empty line.

**Pull request merged**
