### PR TITLE
Replace auction using a single SQL query

### PR DESCRIPTION
**Pull request by squadgazzz**
Alternative to https://github.com/cowprotocol/services/pull/2972 to be tested in order to speed up the auction replacement process.

- Replaces `TRUNCATE` with `DELETE` which should be more performant for small tables
- Uses a single combined SQL query.

> [!IMPORTANT]
> Should not be merged until a positive impact is confirmed.

### CODE REVIEW

**Comment by squadgazzz** [comment]
Shows better results.
Sepolia(~17:47 https://github.com/cowprotocol/services/pull/2972 deployed, ~18:06 this PR deployed):
image

Prod(deployment at ~18:08):
image

**Comment by MartinquaXD** [comment]
Interesting that this had way less of an impact on prod. Maybe the auction size is a very significant factor here?

**Comment by squadgazzz** [comment]
> Interesting that this had way less of an impact on prod. Maybe the auction size is a very significant factor here?

I assume so. The size of the json on prod is almost 1MB.

**Review by MartinquaXD — APPROVED** [review]

**Review by sunce86 — APPROVED** [review]
Code lg.

**Pull request merged**
