### PR TITLE
Replace #[serde(rename_all = "lowercase")] with #[serde(rename_all = "camelCase")]

### PR DESCRIPTION
**Pull request by devansh1401**
I have made the following changes to this pull request:

- Replaced all occurrences of `#[serde(rename_all = "lowercase")]` with `#[serde(rename_all = "camelCase")].
- Ensured that the changes maintain the readability and functionality of the code.

This pull request addresses the concern raised about enum variant readability and serialisation. The changes improve the codebase's consistency and enhance its clarity.

Please review the changes, and I'm open to any feedback or adjustments to ensure the code's quality and maintainability. Thank you for your time and consideration.

### CODE REVIEW

**Comment by devansh1401** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by devansh1401** [comment]
recheck

**Comment by sunce86** [comment]
Apparently you somehow entered hidden `\u`. Just copy-paste the whole line from some other place and you should be good to go.

**Comment by devansh1401** [comment]
@sunce86 
Done with that, but some of them are still failing with different issues.

**Comment by sunce86** [comment]
Will be taken care of in https://github.com/cowprotocol/services/pull/2056

**Pull request closed without merging**
