### PR TITLE
Disable AssetFlow rule.

### PR DESCRIPTION
**Pull request by sunce86**
# Description
During colocation tests, we noticed that some of the solutions were discarded because of this rule that does not exist for legacy driver.

We want first to make sure that all existing legacy driver features are working, before introducing new rules.

### CODE REVIEW

**Review by fleupold — COMMENTED** [review]
Can we fully remove all asset flow related code (I quickly checked and it doesn't look like much)? 
We have in the past too many times created these temporary half-assed deletions which end up staying forever and our codebase became confusing and messy because of this.

The code is stored in version control, so putting the logic back wen we want it should be trivial.

**Comment by sunce86** [comment]
I had a feeling you will suggest that 😄 
Can do that, although I think a lot of code will be removed.

**Comment by fleupold** [comment]
image

**Review by fleupold — APPROVED** [review]
I can still see some relicts when grepping `asset flow`

image

Could you remove these as well please?

**Pull request merged**
