### PR TITLE
Solver engine s3 upload

### LINKED ISSUE #1752: Decide how to proceed with S3 upload with colocation
We are currently uploading auctions to S3 in the `solver` pod. When we switch over to colocation this pod will cease to exist.
That means we either stop uploading auctions to S3 or we have to move that logic somewhere else.

Conceptually the natural choice would be to move that logic into the `autopilot`. But the `autopilot` does not really have the required data to generate the current format. The current format would be generated in the `legacy` solvers wrapper in the colocated world so very far removed from the `autopilot`.
So in conclusion the S3 upload still poses a bunch of questions.

### PR DESCRIPTION
**Pull request by fleupold**
# Description
For debugging purposes it is useful to have access to historic auction instances in the legacy format (pre solver/driver co location) as a bunch of internal checks (EBBO and the like) still use the old format.

While we should change these scripts to work on the new solver engine dto, we can - for the time being - continue to upload the legacy instance files to S3 like we did pre co-location.

cc @fhenneke @harisang 

# Changes

- [x] Create Persistence infra in solvers crate
- [x] Allow legacy solver to specify S3 upload config
- [x] If set, upload legacy instance to S3 

## How to test
Ran a shadow setup locally, observe files getting uploaded to https://staging-bucket-133876976458.s3.eu-central-1.amazonaws.com/legacy/8254181.json

## Related Issues

Fixes #1752

### CODE REVIEW

**Review by sunce86 — COMMENTED** [review]
Is this uploading the same instance file (well almost the same, maybe different deadline) for each external solver for each auction?

**Comment by fleupold** [comment]
It's only uploading a file if configured. The plan would be to only configure it for a single solver engine (potentially even one that is not competing)

**Comment by squadgazzz** [comment]
> Is this uploading the same instance file (well almost the same, maybe different deadline) for each external solver for each auction?

Just a nit: to check if the file already exists in the following function to avoid unnecessary uploads in case of errors in the configuration:
https://github.com/cowprotocol/services/blob/main/crates/s3/src/lib.rs#L36-L56

**Review by squadgazzz — APPROVED** [review]

**Comment by fleupold** [comment]
> Just a nit: to check if the file already exists in the following function to avoid unnecessary uploads in case of errors in the configuration:

I'm not sure this is possible in a concurrency safe way. Different solver engines run in different processes (and thus have no means of coordinating) and are all called roughly at the same time so they'd likely race to upload. It's possible that all of them check the file doesn't yet exist and then go ahead uploading it in parallel. 

As far as I can tell there is no "put if not exists" operation inside S3. But in the worst case, we will still end up with one file (since they will all be using the same auction ID)

**Pull request merged**
