### PR TITLE
Remove `mature` functionallity for orders

### PR DESCRIPTION
**Pull request by sunce86**
Completely removes the maturity of orders. 

In some of the previous PR regarding mature orders several people mentioned removing this feature completely.
Also the removal was discussed on slack.

We also have a pending bug for maturity orders: https://cowservices.slack.com/archives/C0375NV72SC/p1670445420283239?thread_ts=1670444572.860879&cid=C0375NV72SC

Instead of pursuing the bugfix I figured to remove it completely since not really essential for protocol.
Also OK if you have arguments to keep it (although I figured having ready PR would push us to decide in its favor :D )

### CODE REVIEW

**Comment by nlordell** [comment]
cc @harisang, is this something we are committed to? AFAIK, there were still some open questions about this.

Can we first configure the maturity to be `0` and analyze how this impacts our batch sizes?

**Review by nlordell — COMMENTED** [review]
Code changes look great! ✂️.

**Comment by poolpitako** [comment]
+1000 let's simplify!

**Review by MartinquaXD — APPROVED** [review]
Love it! 🧹

**Comment by harisang** [comment]
> cc @harisang, is this something we are committed to? AFAIK, there were still some open questions about this.
> 
> Can we first configure the maturity to be `0` and analyze how this impacts our batch sizes?

Sorry, completely forgot to respond to this.

I think we should do this. Once it's live, we can keep an eye on it for a day, and if avg batch size drops by a lot, then we can revert if needed.

**Review by nlordell — APPROVED** [review]

**Comment by vkgnosis** [comment]
What's the status of this? Did we implement it in some other way?

**Comment by sunce86** [comment]
Closing as being a copy of https://github.com/cowprotocol/services/pull/1221

**Pull request closed without merging**
