### PR TITLE
Only count winner if we actually got a quote

### PR DESCRIPTION
**Pull request by MartinquaXD**
Currently we sort price estimate by some condition and pick the estimator that provided the first entry as the winner.
However, it can happen that the first entry is an error. That happens if all estimators returned an error. In that case it doesn't make sense to say some solver provided a "winning error".

This PR makes it so that metrics related to winning are only incremented if the best solution is not an error.

I decided to leave the arguably somewhat misleading log of "winning price estimate" unchanged because it's only used for debugging and introducing a new log specifically when all solvers produce errors seems to do more harm than good.

### Test Plan
CI

### CODE REVIEW

**Review by sunce86 — APPROVED** [review]

**Comment by sunce86** [comment]
> I decided to leave the arguably somewhat misleading log of "winning price estimate" unchanged because it's only used for debugging and introducing a new log specifically when all solvers produce errors seems to do more harm than good.

Why not putting in under `result.is_ok()`?

**Review by nlordell — APPROVED** [review]

**Comment by MartinquaXD** [comment]
> Why not putting in under result.is_ok()?

I think I sparked confusion unwillingly. The `winning price estimate` already contains the whole result. So we already have the information whether or not we have an error in the log.
[error log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/c0e240e0-d9b3-11ed-b0e6-e361adffce0b/cowlogs-prod-2023.08.16?id=jJxY_okB9jDEhm2yzsKc)
[ok log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/c0e240e0-d9b3-11ed-b0e6-e361adffce0b/cowlogs-prod-2023.08.16?id=8mNa_okBgmOFBpCY1Vn0)

**Comment by sunce86** [comment]
Yes but we also have `new price estimate` log that logs every estimate so I was wondering do we need ever to know the best error solution.

**Comment by MartinquaXD** [comment]
> Yes but we also have new price estimate log that logs every estimate so I was wondering do we need ever to know the best error solution.

It's not so much that we want to know which error was the best but rather having a single convenient log to query in order to know exactly who provided the quote for an order. Either we know the actual winner (if `result.is_ok()`) or we know that none of them provided a quote if (`result.is_err()`). Since we already have all the info in a single log I didn't see the need to add another log for that.

**Pull request merged**
