### PR TITLE
Add tokens and fee tier to UniswapV3 subgraph query

### PR DESCRIPTION
**Pull request by sunce86**
This PR adds token0, token1 and fee tier to subgraph query.
This is needed because, currently, cache is populated with entries that don't have these fields (token0, token1, fee tier) here [(1)](https://github.com/cowprotocol/services/blob/4418d1cd588009c5a9e89107443c6d5ea257f339/crates/shared/src/sources/uniswap_v3/pool_fetching.rs#L141) making this [(2)](https://github.com/cowprotocol/services/blob/4418d1cd588009c5a9e89107443c6d5ea257f339/crates/shared/src/sources/uniswap_v3/pool_fetching.rs#L206) line to fail.

Since the same struct `PoolData` was used for two different queries, these fields were optional. Now, both queries require token0,token1,fee tier, so optionality is removed.

UT passing.

### CODE REVIEW

**Review by MartinquaXD — APPROVED** [review]
I think always fetching `token0`, `token1` and `fee` seems reasonable (this information seems generally important) but when the requirements for the different queries diverge too much you could consider introducing unique data types for each query. That way you don't have to worry about optionals or fetching too much data because every query only has to fetch exactly what it needs.

**Review by vkgnosis — APPROVED** [review]
I couldn't parse the title of the PR but code change looks fine

**Comment by nlordell** [comment]
Could you please fix the PR title and provide a little more context in the description? I don't really understand the title and its not immediately clear to me why we now need this data (and didn't need it before).

**Comment by sunce86** [comment]
> Could you please fix the PR title and provide a little more context in the description? I don't really understand the title and its not immediately clear to me why we now need this data (and didn't need it before).

Done. Sorry bout that.

**Review by nlordell — APPROVED** [review]
Thanks for the updated description! Changes make sense.

**Pull request merged**
