### PR TITLE
Refactor auction metrics with macro

### PR DESCRIPTION
**Pull request by vkgnosis**
The macro approach is superior to the trait approach. When we introduced the macro we didn't convert all existing trait metrics over.

### Test Plan

CI

### CODE REVIEW

**Review by nlordell — COMMENTED** [review]
Code changes look good. Could you add a short description describing the motivation of the PR (even if it seems obvious to us know, it might not be obvious to someone joining a few months for now that don't have the context "this is how we used to do metrics, and this is how we do metrics now").

**Comment by vkgnosis** [comment]
I didn't do that because I would be pasting exactly the same blurb for all of the metric refactoring PRs which feels silly. If you think it is useful I'll add it.

**Comment by nlordell** [comment]
>  If you think it is useful I'll add it.

I do think it should have enough context for someone to come and understand this change and not necessarily know what "macro approach" and "trait approach" are.

> I didn't do that because I would be pasting exactly the same blurb for all of the metric refactoring PRs

This is valid point. Maybe in 1 PR you could have a more complete description and in other PRs just reference that original description so its easy to find the original context for the change.

**Comment by vkgnosis** [comment]
I feel that explaining the full macro vs trait approach is not necessary. That is obvious from the contents of the PR where you see a trait getting deleted and a struct with a macro (derive) added. Docs.rs tells you what the macro does.
Is the description good enough now in your eyes?

**Review by nlordell — APPROVED** [review]

**Pull request merged**
