### PR TITLE
`http_solver`: optimal graph algo using BFS

### PR DESCRIPTION
**Pull request by wthrajat**
### Description

Fixes a todo: earlier, the code used a more iterative approach with HashSet manipulations
Now: we construct a graph and use BFS to explore connected tokens.
Hopefully this is more optimal graph algorithm.

### Changes

Implemented a graph data structure and BFS to efficiently find tokens connected to the native token.
## How to test
Tests passed (run using):
```sh
cargo test --package solver --lib -- solver::http_solver::instance_creation::tests --nocapture
```

### CODE REVIEW

**Comment by wthrajat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wthrajat** [comment]
Rechecking the CLA status...

**Review by MartinquaXD — COMMENTED** [review]
Thanks for your contribution!
Since the TODO comment was concerned with performance did you measure how the new solution compares to the old one?
I'm a bit concerned all the hashing might be quite the overhead also this would use a lot of memory.

**Comment by wthrajat** [comment]
@MartinquaXD Not sure of the best way to benchmark it. I used [hyperfine](https://github.com/sharkdp/hyperfine) for benchmarking unit tests times for this branch and `main` branch.
And got the following results:

#### `main` branch:
```sh
~/rust/cowprotocol/services  on main
╰─❯ hyperfine 'cargo test --package solver --lib -- solver::http_solver::instance_creation::tests --nocapture' ─╯
Benchmark 1: cargo test --package solver --lib -- solver::http_solver::instance_creation::tests --nocapture

  Time (mean ± σ):     11.784 s ± 36.549 s    [User: 55.875 s, System: 2.913 s]
  Range (min … max):    0.220 s … 115.804 s    10 runs
```
Screenshot:
2024-02-13-01 40 45-screenshot
<hr>


#### `optimal_graph_algo` (this) branch:

```sh
~/rust/cowprotocol/services  on optimal_graph_algo
╰─❯ hyperfine 'cargo test --package solver --lib -- solver::http_solver::instance_creation::tests --nocapture'                      ─╯
Benchmark 1: cargo test --package solver --lib -- solver::http_solver::instance_creation::tests --nocapture

  Time (mean ± σ):     10.397 s ± 32.152 s    [User: 39.119 s, System: 2.047 s]
  Range (min … max):    0.222 s … 101.904 s    10 runs
```
Screenshot:
2024-02-13-15 21 57-screenshot

<hr>
Both the tests were run after a fresh build, eliminating the chance of using cache.

### Result

There is a slight time latency improvement after the PR.
1. The maximum time has been improved by `13.900 sec`
```math
115.804 - 101.904 =  13.900
3. If considering `mean time`, this has been improved by `11.77%`
```math
((11.784 − 10.397​) / 11.784) * 100
```
However, I'm not too sure how to test the memory usage concretely. I could take a look at the memory usage during both the test runs but that would

**Comment by wthrajat** [comment]
@MartinquaXD Not sure of the best way to benchmark it. I used [hyperfine](https://github.com/sharkdp/hyperfine) for benchmarking unit tests times for this branch and main branch.
And got the following results on `12 runs` sample:

#### `main` branch:
2024-02-13-16 51 39-screenshot

<hr>

#### `this` branch:
2024-02-13-16 52 34-screenshot

<hr>

### Result

There are some noticeable time improvements:

1. `minimum time` has gone down from `226 ms` to `215 ms`
2. `maximum time` has gone down from `264 ms` to `236 ms`
3. `mean time` extremes have been improved by *5.1%*
```math
\text{} \frac{237.6 - 225.5}{237.6} \times 100 = 5.1 %
```

However, I'm not too sure how to test the memory usage concretely (AFAIK, [criterion](https://docs.rs/criterion/latest/criterion) doesn't support memory usage). I could take a look at the memory usage during both the test runs (on a quick look, doesn't seem to be a noticeable difference) but that would not be too accurate. If you have any ideas, feel free to suggest, I'll give them a shot.

Also if the original TODO meant some other optimization, feel free to point me to that.
Thanks!

**Comment by MartinquaXD** [comment]
> Not sure of the best way to benchmark it.

This is not so easy. I just tried to do it but it turns out this code is actually not used anymore. The `solver` crate is currently being phased out. We have not been running it for some time but can't delete it yet because some other crates are reusing code from it. I was under the impression the code was still in use by a different component but that is not the case.
Sorry that this ended up wasting your time. :/
Will open a PR to get rid of the unused code so nobody else runs into the same issue.

**Comment by wthrajat** [comment]
@MartinquaXD 
> Sorry that this ended up wasting your time. :/

No it's chill, I'm in the learning phase so it doesn't hurt.
I see that `solver` crate has been removed by the PR #2405. So I guess I should close this now.
Thanks for the review!

**Pull request closed without merging**
