### PR TITLE
Move some U256 conversions into own crate

### PR DESCRIPTION
**Pull request by vkgnosis**
In order to disentangle some dependencies I'm moving this to it's own crate. The plan is to move the BigDecimal <-> U256 conversion into the database crate without making it depend on shared.

Some of the conversion implementations have been slightly changed.

### Test Plan

CI, existing tests

### CODE REVIEW

**Review by MartinquaXD — COMMENTED** [review]
Nice idea but why not also move the other conversion function for `primitive_types` and the extension trait as well?
IMO it would be cool to unify those conversions as much as possible (ideally only a single crate).

**Comment by vkgnosis** [comment]
I decided that based on how many crate will use it. BigDecimal, H160, H256 is only relevant for things touching the database so I want those conversions to be in the database crate. The extension trait I think was only really used in one place so I feel it can stay local to there.
Can always change this stuff later. The main reason for this change at the moment is that I wanted the U256 -> num::BigRational etc functions out of shared.

**Review by MartinquaXD — APPROVED** [review]

**Review by nlordell — APPROVED** [review]
LGTM.

~Might be worth already adding the `bigdecimal` conversions as well (although I'm unsure if they are as widely used). Either way, approving the PR as is.~

**edit**: I saw this after making my comment:
> The plan is to move the BigDecimal <-> U256 conversion into the database crate without making it depend on shared.

I think it still might worth be moving BigDecimal <-> U256 to this crate (since, if I remember correctly, we make light use of it in the `solver` crate for liquidity, specifically with Balancer that uses fixed point math) and `bigdecimal` is not a big "extra" dependency to pull in. Don't feel strongly about this at all though.

**Comment by vkgnosis** [comment]
I don't see it being used in the solver crate. I wouldn't mind moving it into here much, just a tiny bit. So if we end up needing that in several places we can totally move it here too.

**Comment by nlordell** [comment]
> I don't see it being used in the solver crate.

I think I'm remembering wrong.

I was thinking of the `fee` in the HTTP solver model:
https://github.com/cowprotocol/services/blob/03a4bc51806dfd03d9ba46ed65bb3136908691b4/crates/shared/src/http_solver/model.rs#L47-L48

Where we convert from U256 (actually weird fixed point notation) to a rational: https://github.com/cowprotocol/services/blob/03a4bc51806dfd03d9ba46ed65bb3136908691b4/crates/solver/src/solver/http_solver.rs#L300

**Pull request merged**
