### PR TITLE
Fixes and simplifications for RequestSharing

### PR DESCRIPTION
**Pull request by MartinquaXD**
## Fixed Cache Size Metric
The `RequestSharing` component was the prime suspect for a significant memory leak due to its metric displaying that the internal cache grows indefinitely.

After wasting waaay too much time on this it appears that the metric simply has a bug. If somebody calls `shared_or_else()` and there is already an **outdated** `WeakShared` item in the cache that has not been removed by GC we'd:
1. build a new future
2. `insert()` it into the cache
3. increase the metrics for the cache size by 1

But in this specific edge case the `insert()` would actually overwrite an existing item in the cache and not add a new one so increasing the metrics by 1 is actually over counting the number of cached items. Over time this accumulated more and more and made it look like the component had a serious memory leak.

The easy fix is to just not use `inc()` and `sub()` for adjusting the cache size metrics but rather `set(cache.len())` since that is absolutely fool proof.

## Removed 1 `RequestSharing` instance
The `TradeEstimator` has a `RequestSharing` and contains a `TradeFinder` which also contains a `RequestSharing` instance. This double caching is overly complex and due to that I already suspected it 3 times that it might be related to a memory leak. Now only the `TradeFinder` uses `RequestSharing` which is the component that actually sends the HTTP requests.

### CODE REVIEW

**Comment by fleupold** [comment]
Maybe this is a stupid question, but how important is this request sharing component for performance (ie could we live without it?). Iirc the same concept could be implemented in infra on the nginx egress layer.

**Comment by MartinquaXD** [comment]
> how important is this request sharing component for performance

It doesn't kick in very often but my understanding is every little bit helps to keep our RPS in line.

> Iirc the same concept could be implemented in infra on the nginx egress layer.

TBH I'm not so keen on that approach anymore. Last time we updated some logic in the solvers that approach broke and it wasn't even obvious it did. The nginx approach might seem better at the moment because it helps even with multiple instances of orderbook / autopilot but with the new pricing service in mind I think it would be better to use this caching solution than the nginx approach. Will merge this PR as it's a low risk change but I'm open to discussing this further.

**Comment by fleupold** [comment]
> It doesn't kick in very often but my understanding is every little bit helps to keep our RPS in line.

If this component is not absolutely required, have we tried to disable it completely just to verify this would solve our memory leak (my intuition is still that it stems from warp or axiom on the incoming request side). This would give us more confidence to keep pounding this component.

**Comment by MartinquaXD** [comment]
> have we tried to disable it completely just to verify this would solve our memory leak

Yes. Tried it and it didn't make a difference. When looking into this it seemed like we are accumulating more and more tasks that don't terminate. Also for every task that hyper spawns it creates 1 channel to manage graceful shutdown requests.
Unfortunately I was not able to debug this thoroughly because `tokio-console` I used for that seemed to get overwhelmed pretty quickly.
Another possible good starter task would be to use expose the metrics of the tokio runtime ourselves. That way we could plot the number of tasks handled by the runtime to see if it's continues to increase or top out at some point.

**Pull request merged**
