### PR TITLE
Suggestion to update PR template

### PR DESCRIPTION
**Pull request by sunce86**
# Description
I noticed these are some of the common things we forget about (at least myself). Do you think we should put those as acceptance tests for each PR?

### CODE REVIEW

**Comment by mfw78** [comment]
We already have acceptance criteria in issues (ie. the improvement template). Is it suitable for us to duplicate this?

I would also suggest that most of the body for a PR should be in HTML comment tags so when we inevitably forget to remove something not applicable, it isn't visible :grinning:

**Comment by MartinquaXD** [comment]
I think having such a list would be very helpful but I'm not sure if we should bake it into the template.
Especially since most of these items would not apply to all PRs.

**Comment by fleupold** [comment]
I'm also not a huge fan of adding this to the general PR template (it's already a lot to fill out). Instead, we could have an action that checks e.g. if a dto was changed and posts a comment on the PR to remind the author to update the specs (it could even check if the specs were in fact updated or not on only post if it wasn't)

**Comment by fleupold** [comment]
Superseeded by https://github.com/cowprotocol/services/pull/2364 which should allow to add more "conditional reminders" on PRs

**Pull request closed without merging**
