### PR TITLE
Get rid of deprecated solvable_orders routes

### PR DESCRIPTION
**Pull request by vkgnosis**
In the metrics I see that we still get requests to this route but in Kibana I don't see any nginx logs. I think that means that some internal service is requesting the route but I couldn't find it in this repo or the kubernetes repo. If we continue to be unable to find it we can still merge and hopefully see it logs afterwards.

### Test Plan

CI

### CODE REVIEW

**Comment by MartinquaXD** [comment]
Looks like the dune bridge is still using the endpoint: https://github.com/cowprotocol/dune-bridge/blob/4c37f087ba345f6d34efd04fa5e8e44b740360c5/src/referral_maintenance.rs#L173-L192

**Comment by vkgnosis** [comment]
Thank you for finding that. Created issue https://github.com/cowprotocol/dune-bridge/issues/29 .

**Review by nlordell — APPROVED** [review]

**Review by MartinquaXD — APPROVED** [review]
I'm fine with the code change but maybe we should delay merging this until the analytics team had some time to react to the new issue.

**Comment by vkgnosis** [comment]
Agree we should wait for them to get a chance to fix this.

**Review by sunce86 — APPROVED** [review]

**Pull request merged**
