### PR TITLE
Less strict price violation check

### PR DESCRIPTION
**Pull request by fleupold**
This PR changes our price violation check in a non-trivial way. The check is used to ensure we are not trading a set of very liquid pairs (mainly stables and ETH) at prices that are too far off the current market price. This is meant to protect users, whoever it has also caused significant friction during the highly volatile times on Saturday, where a lot of valid solutions were dismissed because they violated this check.

Instead of iterating over all possible pairs in the clearing price vector and verifying that they don't differ from the external prices, we now just iterate over all possible user orders and check that - if their buy and sell token are in the list of tokens to be checked - their execution isn't **worse** than the external price + tolerance. This means e.g. that single order solutions in which solvers find a solution that is much better than the estimated price are still allowed to settle. 

Moreover, it removes the need for solvers to "normalize" their price vector (e.g. if tradeA swapped 1ETH for 10GNO and trade B swapped 1USDC for 1DAI, a price vector of (ETH: 10, GNO: 1, USDC: 1, DAI: 1) would have failed this check even though there wa no trade between USD and ETH or GNO)

### Test Plan

Unit test

### Release notes

We should carefully observe if the remaining price violation settlements are real and there is no negative effect of other, now valid settlements

### CODE REVIEW

**Comment by fleupold** [comment]
I have read the CLA Document and I hereby sign the CLA

Recheck

**Comment by fleupold** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vkgnosis — APPROVED** [review]

**Review by nlordell — COMMENTED** [review]
Sorry for taking a while to review this.

One reason that we checked upper bounds as well was to prevent solvers from settling orders at "too good to be true" prices on very liquid pairs (which should never happen). Some examples of issues this has caught in the past were surplus distribution bugs where surplus for a large order would be given to a small DAI <> USDC order, effectively settling it way above the 

Are we sure we want to remove restrictions from the upper bound as well?

Other than that, the changes are very nice.

**Comment by fleupold** [comment]
> Some examples of issues this has caught in the past were surplus distribution bugs where surplus for a large order would be given to a small DAI <> USDC order, effectively settling it way above the

In the case of surplus distribution bugs, I'd expect someone else to receive a price that is worse than the reference price. I see that this might not be the case when a large trade's surplus is absorbed by a small trade's surplus (the large trade may still be within the bound). On the other hand, this particular check has caused a good amount of trouble in the past rejecting valid solutions where the user would have been much better off (our baseline price estimate can be really bad in volatile times), so I'd be somewhat keen to try it more lenient.

**Review by nlordell — APPROVED** [review]

**Pull request merged**
