### PR TITLE
Fix index for ethflow_orders table

### PR DESCRIPTION
**Pull request by sunce86**
# Description
Previously index was created on a wrong table: "orders" instead of "ethflow_orders":
https://github.com/cowprotocol/services/blob/main/database/sql/V031__create_ethflow_orders.sql#L11

Should speed up the OPEN_ORDERS query, although not sure how much.

### CODE REVIEW

**Review by fleupold — APPROVED** [review]

**Review by Mateo-mro — APPROVED** [review]

**Review by squadgazzz — APPROVED** [review]
Gave it a try locally, didn't really help(still have 3-4s to execute).

**Comment by squadgazzz** [comment]
We have 2 identical indexes: user_valid_to and order_valid_to, right? One should be dropped.

**Comment by sunce86** [comment]
Relevant to https://github.com/cowprotocol/services/issues/2831#issuecomment-2251188741

**Comment by sunce86** [comment]
> We have 2 identical indexes: user_valid_to and order_valid_to, right? One should be dropped.

Dropped `user_valid_to`

**Pull request merged**
