### PR TITLE
Add temporary logs for Quasimodo encoding issue

### PR DESCRIPTION
**Pull request by sunce86**
Add temporary logs to better inspect encoding flow for Quasimodo solutions.

More context [here](https://cowservices.slack.com/archives/C0375NV72SC/p1667386363586569)

### Release notes

This PR should not be part of the next week release, meaning revert PR is expected to be merged until the end of week.

### CODE REVIEW

**Review by nlordell — COMMENTED** [review]
I think this kind of debugging means that we don't have enough observability in our services. Maybe we can start using `trace!` logs more generously to help find these issues and enable/disable them with configurations.

Approving as I don't want to block progress with this bug.

**Review by nlordell — APPROVED** [review]

**Review by vkgnosis — COMMENTED** [review]
If you feel you need this I'm ok with temporarily merging but I'm not sure if it's the correct approach to debugging it.

It seems better to me to make these logging changes locally and run the system locally with Quasimodo in shadow mode. That way you can debug as much as you want to without relying on the real system.

**Comment by nlordell** [comment]
> Did you consider that? Does it have problems compared to this approach?

I think there is a bit more context from @sunce86 in Slack:

> After running the Quasimodo locally I could not reproduce the problematic behavior (encoding was done as expected). I need these logs to inspect more different cases.

**Comment by sunce86** [comment]
Thanks for the comments, I do agree with them. This was actually the last thing I wanted to do because I am aware it's not a proper way to go.

I did try with unit test using examples of problematic Quasimodo solutions, also tried with local setup with no luck.
What I noticed is that we do sometimes have `UniswapV3Interaction` properly encoded with shadow solver, meaning it does not happen always.

**Pull request merged**
