### PR TITLE
Simplify orderbook test getting rid of mocked components

### PR DESCRIPTION
**Pull request by vkgnosis**
by splitting up the function into IO and non IO.

### Test Plan

CI, existing test

### CODE REVIEW

**Review by MartinquaXD — COMMENTED** [review]
I'm not sure about this one. On the one hand the helper function is way nicer to test but on the other hand we now have no test asserting that `database.replace_order()` actually gets called.

**Review by nlordell — COMMENTED** [review]
I don't necessarily disagree with the refactor (specifically, I like the new `check_valid_replacement` function).

That being said, I don't think its worth removing tests since there are code-paths unrelated to IO such as what happens when we don't find the cancelled order (not IO but data specific).

In general, I agree with the sentiment that testing can be cumbersome with all the mocking and mocking interfaces, and I think restructuring code to have "pure" functions that are easier to test and used within the IO/non-pure functions goes a long way.

**Comment by vkgnosis** [comment]
I refactored this test while changing the orderbook struct to not take individual Arc<dyn> trait objects related to database function in favor of taking the single orderbook::Postgres struct on which we implement all of it. Since that isn't a trait object it can't be mocked and this was the only reason we needed this to be mockable. Since you'd like to keep this test  can change this PR to make the test a "postgres" test so that it can use the real database instead of mocking.

**Comment by vkgnosis** [comment]
> That being said, I don't think its worth removing tests since there are code-paths unrelated to IO such as what happens when we don't find the cancelled order (not IO but data specific).

The function returns early. I still feel this is simple enough to not need a test and the existing only tested this accidentally, not intentionally.

**Pull request closed without merging**
