### PR TITLE
orderbook: instanciate code fetcher once

### LINKED ISSUE #2429: chore: Share `CodeFetcher` in orderbook
### Background
Currently we create one instance of `CodeFetcher` in the price estimator factory and another one for the `OrderValidator` in the orderbook. There is no reason these need to be separate instances so by sharing 1 instance in both contexts we could reduce the number of RPC calls we issue for fetching code at a given address.

### PR DESCRIPTION
**Pull request by ybensacq**
# Description

Reduce the number of RPC calls by instantiating the code fetcher only once.

# Changes

- [ ] Instanciate code_fetcher in run (orderbook)
- [ ] Pass it to PriceEstimatorFactory

Fixes #2429

### CODE REVIEW

**Comment by ybensacq** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by MartinquaXD** [comment]
Thanks for the contribution! Looks good already.
Just needs to be formatted correctly using `cargo +nightly fmt --all` since we rely on a few nightly features in our formatting rules.

**Comment by ybensacq** [comment]
@MartinquaXD  ok that's done.

**Comment by squadgazzz** [comment]
Kindly run all of these in order to make sure the code compiles and works properly:
```
cargo clippy --locked --workspace --all-features --all-targets -- -D warnings
cargo build
cargo test
```

**Comment by ybensacq** [comment]
@squadgazzz yes just dit that as well and fixed the issue.

**Comment by ybensacq** [comment]
@squadgazzz do you have an idea why forked node test is failing?

**Review by fleupold — APPROVED** [review]
I believe the forked test is failing because your PR doesn't have access to the fork url secret (it will likely pass once merged).

**Comment by ybensacq** [comment]
@fleupold ok thank you.

**Review by squadgazzz — APPROVED** [review]
LGTM

**Review by MartinquaXD — APPROVED** [review]

**Pull request merged**
