### PR TITLE
Add solver address to solver competition

### PR DESCRIPTION
**Pull request by sunce86**
This PR adds solver address to each solution saved to solver competition db.

It allows data team to do queries more efficiently and avoid matching the `solver` name with the list of solver addresses.

### CODE REVIEW

**Comment by vkgnosis** [comment]
We should think about whether this makes sense. Solvers can change their address. Some solvers might not have a single address that they submit from like if they use Gelato (?). From this POV it is more correct to keep using the solver name, even if that means a slight overhead for the data team. On the other hand, maybe a solver can also change it's name. This change isn't problematic, but I'm not sure if it makes sense.

**Comment by bh2smith** [comment]
If the new CIP is going to retroactively distribute remaining rewards to solvers that submitted non-winning solutions, we would need to know an address for these solutions that never made it on chain to attribute to them. Yes. Solvers can change their address, but it is the solver who solved the batch that should be attributed to the retroactive rewards.

**Review by bh2smith — APPROVED** [review]

**Comment by vkgnosis** [comment]
The name and the address are connected. We have a document where we list all solver names, their address, their reward address. The question is what the best "primary" key to identify solvers is. It could be any of these fields.

**Review by nlordell — APPROVED** [review]

**Comment by nlordell** [comment]
Personally, I think `address` is a better unique identifier for this (as it is how they are identified on-chain).

Agree this means we can technically drop the `name`, although it is useful.

**Comment by nlordell** [comment]
> It allows data team to do queries more efficiently and avoid matching the solver name with the list of solver addresses.

Hmm, given this is the motivation, I'm not sure this is the correct way to do it. I don't think the `solver_competitions` table was intended to be anything more than debug data.

**Comment by bh2smith** [comment]
> Hmm, given this is the motivation, I'm not sure this is the correct way to do it. I don't think the `solver_competitions` table was intended to be anything more than debug data.

Note that, we do not currently have al alternative solution for looking up past competitions with this retroactive disbursement of remaining rewards balance. So this table will likely be the place we must go to get a glimpse of historical solver performance metrics.

**Review by ennmichael — APPROVED** [review]
:shrug: Code is OK, depends on what we decide to do

**Comment by sunce86** [comment]
> If we need something for the core protocol like solve payouts, we should add it to a separate table so that it is clear that it isn't generic debug data.

I addressed this here: https://github.com/cowprotocol/services/pull/1166#issuecomment-1423969119
With that I believe it is ok to merge this PR.

**Pull request merged**
