### PR TITLE
Fix NaiveSolver LimitOrder bug

### PR DESCRIPTION
**Pull request by fleupold**
Fixes NaiveSolver "High Simulation Failure Rate" alerts .

There is a bug in the way the NaiveSolver validates if a solution candidate is acceptable (ie satisfies the order's limit price). Specifically, it doesn't account for surplus fee when checking the limit price. This can lead to solutions being generated which will later on fail on the smart contract level and therefore cause simulation failure.

The fix here is very dirty, and likely not the right way to address this problem. Given that our "order" data model is no longer a dumb object (but instead contains a bunch of conditional semantics based on the order metadata), we should probably no longer allow accessing raw fields directly in dispersed logic code (too much risk of forgetting to incorporate a fee in some call-sites). Instead we should have some abstraction that exposes something like "sell amount after fee" which can then implement conditional logic. I found the "OrderConverter" abstraction, however this is not easily available here.

This PR is more a demonstration of the problem and should spark as a discussion on how to properly fix this bug.

### Test Plan

Unit test

### CODE REVIEW

**Comment by fleupold** [comment]
As a note, the same logic change was forgotten in the Alerter, which now also alerts when an order can be settled according to 0x "before surplus fee" (even if it is not tradable after deducting the surplus fee)

**Review by vkgnosis — APPROVED** [review]
I think we should merge the fix like this while keeping in mind your comment about how this would be easier to prevent in the future.

**Comment by nlordell** [comment]
I think the less dirty approach is to use the other Settlement encoder functions that get the priced user trades (instead of indexing into the clearing price vector):

https://github.com/cowprotocol/services/blob/ed372d91dbbcf82448a836e794a7db521236168b/crates/solver/src/settlement/settlement_encoder.rs#L164-L169

**Comment by nlordell** [comment]
> the same logic change was forgotten in the Alerter

Should be fixed here https://github.com/cowprotocol/services/pull/923. Unfortunately, it was not merged yet 😞

**Comment by fleupold** [comment]
> I think the less dirty approach is to use the other Settlement encoder functions that get the priced user trades

Implemented. It's definitely more elegant however I have less confidence it's correct (it's a bit scary how we have many different way to effectively access the same information on this struct).

> Should be fixed here https://github.com/cowprotocol/services/pull/923. Unfortunately, it was not merged yet 😞

Can we merge it? It's causing unactionable false alerts.

**Comment by nlordell** [comment]
> Can we merge it?

Yes. Will address @vkgnosis's concern and split the limit order price fix into a separate PR.

**Review by nlordell — APPROVED** [review]

**Pull request merged**
