### PR TITLE
Add request id header for rpc requests

### LINKED ISSUE #2519: feat: Add Request ID header to RPC requests for easier debugging
### Problem
Our JSON RPC requests currently don't send any information that would make it easier to track the particular request to debug. Adding the Request ID header to each JSON RPC request will help debug individual failing RPC calls.

### Suggested solution
Add a unique request id header to all JSON RPC calls

This is what our request looks like currently:
```
 {"args":{},"headersIn":{"content-type":"application/json","accept":"*/*","user-agent":"cowprotocol-services/2.0.0","accept-encoding":"gzip","host":"mainnet.eth-node-proxy.svc.cluster.local","content-length":"200"},"headersOut":{},"httpVersion":"1.1","internal":false,"method":"POST","remoteAddress":"10.0.169.177","requestText":"{\"jsonrpc\":\"2.0\",\"method\":\"eth_getLogs\",\"params\":[{\"address\":\"0x9008d19f58aabd9ed0d60971565aa8510560ab41\",\"blockHash\":\"0x467a3a9beff034e6a525451b33c010cc532796bdc709560de6e11d4e7e587db6\"}],\"id\":82969}","status":0,"uri":"/"}
```

### PR DESCRIPTION
**Pull request by rferrandop**
# Description
Add a request id header for the RPC requests.

# Changes

This PR adds the following request HTTP headers on RPC requests:
- `X-RPC-Request-Id` - The unique ID of the RPC request.
- `X-Request-Id` - The top level request id passed as a request header for the RPC request generated.

## How to test

I couldn't find a suitable way to test this. Maybe, it would be useful to create tests for the RPC request execution and assert that those headers are been sending.

## Related Issues

Fixes #2519

### CODE REVIEW

**Comment by rferrandop** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by MartinquaXD — APPROVED** [review]
Thanks for your contribution.
Looks very good!

**Review by squadgazzz — APPROVED** [review]

**Comment by rferrandop** [comment]
Hi, I fixed the code formatting. Now the lint workflow should be working OK.
The `test-forked-node` failed, but I think that is a runtime issue: https://github.com/cowprotocol/services/actions/runs/8709367754/job/23972858160

**Comment by MartinquaXD** [comment]
> The test-forked-node failed, but I think that is a runtime issue

Yeah, unfortunately these tests always fail for external contributions.
Will rebase the PR and merge it.
Regarding the reward: Can you post your reward **gnosis chain** address here or send me a DM on discord (in case you prefer that for privacy reasons)?

**Pull request merged**
