### PR TITLE
Drop access list from `eth::Tx` `Debug` impl

### PR DESCRIPTION
**Pull request by MartinquaXD**
# Description
Drop the `access_list` field from the `Debug` impl because it's pretty noisy and not very helpful for debugging purposes.

### CODE REVIEW

**Review by sunce86 — APPROVED** [review]
> note that Bytes already implements hex string printing

Ah, didn't know. My bad.

**Comment by sunce86** [comment]
The only reason I think it might be smart to have custom debug impl is to drop access list printing since it's not important for the simulation result (except for out of gas error which don't happen)

**Comment by MartinquaXD** [comment]
> The only reason I think it might be smart to have custom debug impl is to drop access list printing since it's not important for the simulation result (except for out of gas error which don't happen)

But this is not the case in the current code either, right?
Happy to drop the access list printing, just checking if I'm missing something here.

**Comment by sunce86** [comment]
> > The only reason I think it might be smart to have custom debug impl is to drop access list printing since it's not important for the simulation result (except for out of gas error which don't happen)
> 
> But this is not the case in the current code either, right? Happy to drop the access list printing, just checking if I'm missing something here.

Yup, not the case, I just noticed it.

**Review by fedgiac — APPROVED** [review]

**Pull request merged**
