### PR TITLE
Require inputs and outputs for interactions in settlement

### LINKED ISSUE #453: Enforce new raw interactions format (i.e., remove backwards compatibility)
It's been some time since the new format about raw interactions was introduced (see, e.g,  PR#[194](https://github.com/cowprotocol/services/pull/194)). Solvers seem to have incorporated the changes, so it would be good to remove this backwards compatibility so that all solvers conform to the new format.

Ideally, we would also need a check that the corresponding input/output amounts for each raw interaction are non-empty, so that constraints regarding token conservation can be checked.

### PR DESCRIPTION
**Pull request by MartinquaXD**
Partly fixes #453

AFAIK the new interaction format changed 2 things in backwards compatible ways:
1. add `inputs` and `outputs` for interactions and assume empty lists if they were not in the serialized response
2. allow serializing call data as an array of numbers (old way) and as a hex string

I see that solvers already adopted the `input` and `outputs` but not the new serialization scheme so this PR will only make `inputs` and `outputs` required but still allows the old `call_data` format.

### Test Plan
Manual test verifying that solutions don't cause deserialization errors.
Updated existing unit test for backwards compatibility (it now only verifies desierialization of the old `call_data` format).

### CODE REVIEW

**Review by nlordell — APPROVED** [review]

**Comment by harisang** [comment]
> I see that solvers already adopted the input and outputs but not the new serialization scheme so this PR will only make inputs and outputs required but still allows the old call_data format.

Which solver is still using the old call_data format? I thought all of them had switched.

**Comment by MartinquaXD** [comment]
> Which solver is still using the old call_data format? I thought all of them had switched.

I think all the solvers sending `call_data` use the old format. Specifically I saw `Atlas`, `CowDexAg`, `Otex` and `PLM`.
This [query](https://logs.cow.fi/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h%2Fh,to:now))&_a=(columns:!(log),filters:!(),index:'63bc0b10-5f93-11e9-bf17-fbe383fc7c9c',interval:auto,query:(language:kuery,query:'log:%20%22considering%20solution%20for%20solver%20competition%22%20and%20log:%20%22call_data%22'),sort:!(!('@timestamp',desc)))) shows the current usage of `call_data`.

**Comment by harisang** [comment]
> > Which solver is still using the old call_data format? I thought all of them had switched.
> 
> I think all the solvers sending `call_data` use the old format. Specifically I saw `Atlas`, `CowDexAg`, `Otex` and `PLM`. This [query](https://logs.cow.fi/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24h%2Fh,to:now))&_a=(columns:!(log),filters:!(),index:'63bc0b10-5f93-11e9-bf17-fbe383fc7c9c',interval:auto,query:(language:kuery,query:'log:%20%22considering%20solution%20for%20solver%20competition%22%20and%20log:%20%22call_data%22'),sort:!(!('@timestamp',desc)))) shows the current usage of `call_data`.

Oh I see, I missed that. But, I also see [this](https://logs.cow.fi/app/discover#/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2022.08.17?id=Nea5qoIBV8CTJiAHjqAI) for example in the logs. Does this mean that this is not actually the json sent from the solver, but an edited-from-the-driver response?

**Comment by MartinquaXD** [comment]
>Oh I see, I missed that. But, I also see [this](https://logs.cow.fi/app/discover#/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2022.08.17?id=Nea5qoIBV8CTJiAHjqAI) for example in the logs. Does this mean that this is not actually the json sent from the solver, but an edited-from-the-driver response?

Yes, what you see does not necessarily have to be the exact string sent by the solver. However, after a quick investigation what I shared is also does not have to be correct.
What we looked at is how **we** would serialize different intermediate representations of the solution the solver sent. However, we are free to serialize our intermediate representation slightly different than what the solver sent so we are none the wiser.
The log message printing the exact string the solver sent doesn't show up in Kibana so I will do some local testing to get the required information. Maybe we can drop the old format after all.

**Comment by harisang** [comment]
> > Oh I see, I missed that. But, I also see [this](https://logs.cow.fi/app/discover#/doc/63bc0b10-5f93-11e9-bf17-fbe383fc7c9c/logstash-2022.08.17?id=Nea5qoIBV8CTJiAHjqAI) for example in the logs. Does this mean that this is not actually the json sent from the solver, but an edited-from-the-driver response?
> 
> Yes, what you see does not necessarily have to be the exact string sent by the solver. However, after a quick investigation what I shared is also does not have to be correct. What we looked at is how **we** would serialize different intermediate representations of the solution the solver sent. However, we are free to serialize our intermediate representation slightly different than what the solver sent so we are none the wiser. The log message printing the exact string the solver sent doesn't show up in Kibana so I will do some local testing to get the required information. Maybe we can drop the old format after all.

Ok, thanks for looking into this! So, if I understand correctly, there is NO way to recover the exact response of a solver? If so, I think this is problematic and I don't see why we do this. I mean, it would just make things easier to have a place to look at exactly what the solvers sent back.

**Comment by MartinquaXD** [comment]
> ... if I understand correctly, there is NO way to recover the exact response of a solver?

Somewhat. This [line](https://github.com/cowprotocol/services/blob/main/crates/shared/src/http_solver.rs#L146) logs the exact solver response but I think the log levels of the `solver` pod are configured such that it gets omitted.
I agree that it makes sense to have that log accessible in Kibana.

**Comment by MartinquaXD** [comment]
My local tests didn't show any solver using the old call data format but I also didn't get a result from every solver.
I would just drop the old call data format as well and see if that causes any problems in staging this week to finish this PR.

**Comment by nlordell** [comment]
> I would just drop the old call data format as well and see if that causes any problems in staging this week to finish this PR.

Lets drop the legacy calldata format in a separate PR so its easier to revert? Otherwise I completely agree.

**Pull request merged**
