### PR TITLE
Use path filter first before method

### PR DESCRIPTION
**Pull request by vkgnosis**
This gives better rejection messages.

### Test Plan

CI

### CODE REVIEW

**Comment by vkgnosis** [comment]
Let's say you get the path and the method wrong. The endpoint is the more significant error so you want to be informed about this first with a 404. The method only matters once we have the correct endpoint so you only want to be informed about it in that case and with a 405. This is what this code change does.

**Review by MartinquaXD — APPROVED** [review]
Thanks for the explanation.
Sounds reasonable. 👍

**Comment by nlordell** [comment]
Might be worth including the additional description https://github.com/cowprotocol/services/pull/280#issuecomment-1157578294 in the commit message and PR description (makes `git blame` to understand these changes have more info).

**Review by nlordell — APPROVED** [review]

**Comment by vkgnosis** [comment]
Added to the squashed commit message

**Pull request merged**
